### ISSUE TITLE
qq群接收信息问题

### ISSUE THREAD

**Issue by StarLeet** [Xposed-Modules-Repo/one.yufz.hmspush#1]
![Screenshot_20221112-194834_QQ~2.png](https://user-images.githubusercontent.com/89691566/201473209-60455ef3-fc4a-4277-8233-7c117a3d58d0.png)

如图所示，我的QQ丢失了群消息，最后一次push是5小时前，但是在2小时前就已经有群消息了，在这期间有二十几条信息，这些信息一次都没有push。

目前仅发现QQ群大概率会丢失信息，其它的都正常。手机内已安装华为商城，hmsCore商城内更新到最新版，且转为系统应用。

系统: 安卓12L
ROM: ArrowOS
手机: 一加7p

**Comment by StarLeet** [comment]
lsp日志已通过邮箱发送。

重点部分在16:00到20:00

**Comment by fei-ke** [comment]
`[ 2022-11-12T14:20:41.464    10061:  2607: 14488 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  notify() called with: context = com.huawei.hms.app.CoreApplication@ee18756, packageName = com.tencent.mobileqq, id = 1389803344, notification = Notification(channel=CHANNEL_ID_SHOW_BADGE shortcut=null contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x110 color=0x00000000 vis=PRIVATE)`

`[ 2022-11-12T20:06:56.081    10061:  2607: 12013 I/LSPosed-Bridge  ] [HMSPush]  NotificationManagerEx  notify() called with: context = com.huawei.hms.app.CoreApplication@ee18756, packageName = com.tencent.mobileqq, id = -1600860150, notification = Notification(channel=com.huawei.hms.pushagent.high91544 shortcut=null contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x110 color=0x00000000 vis=PRIVATE)`

日志中最近两次 QQ 推送在 14点和20点，期间不间断有其他应用的推送日志，表明 HMS 的推送通道是正常的，QQ 不推送的可能原因有很多，HMS 推送策略、QQ 后端推送策略都有可能影响，插件对此没什么可以做的。
