### ISSUE TITLE
在原生系统上推送没有图标

### ISSUE THREAD

**Issue by lingxh** [Xposed-Modules-Repo/one.yufz.hmspush#2]
如图所示，图标显示不正常
而如果让qq在后台走qq自己的推送的话图标是正常的
![Screenshot_20221214-232744_crDroid Home~2](https://user-images.githubusercontent.com/59961232/207638709-d51d6160-3a89-400e-a929-2d3e85d6ba9d.png)

**Comment by kml0798** [comment]
右上角三点》设置》自定义图标开关打开》点击自定义图标文字》右上角导入图标库，连不上要么开梯子要么替换成前几版release介绍里给的网址，导入完就可以了，偶尔会失效，不知什么原因，右上重启hmscore就又好了
